### PR TITLE
Create a first draft if a getting started guide for new users

### PR DESCRIPTION
**Pull request by mraleson**
I hope this is helpful, if not feel free to summarily close.

### CODE REVIEW

**Comment by jeff-dh** [comment]
Yeah, cool!

Let me think about how to integrate it.

It could replace the current readme. Even though it might not be complete (yet), it might be a better starting point than the current readme. It could reference the old one and maybe someone will extend it in the future.

**Comment by mraleson** [comment]
Okay sounds great.

**Comment by jeff-dh** [comment]
I can't push to this pr again...... I double checked it and still.....

do you have any restrictions on your branch? Any ideas?

I'd like to integrate this and would like to do it without creating extra branches like we did last time....

**Comment by jeff-dh** [comment]
https://github.com/jeff-dh/SolidPython/wiki/Getting-Started

I'll try to migrate the docs to the wiki.....

**Pull request closed without merging**
