### PR TITLE
scad_render_to_file forwards file_header

### PR DESCRIPTION
**Pull request by Exr0n**
Update `scad_render_to_file` to forward `file_header` to `scad_render`, to maintain the interface of SolidPython.

I believe this is the correct fix to re-enable the `scad_render_to_file(scad_obj, 'filename.scad', '$fn = 50')` to increase the resolution of rendered curves like cylinders?

### CODE REVIEW

**Comment by Exr0n** [comment]
There is one mention of `$fn` and `segments` in the readme, but I couldn't figure out how to use it.

**Comment by jeff-dh** [comment]
You can set the global `$fn` like this:

```python
>>> from solid2 import *
>>> from solid2.extensions.greedy_scad_interface import set_global_fn
>>> 
>>> set_global_fn(72)
>>> cube() #test it
$fn = 72;
cube();
```

Take a look at the `greedy_scad_interface` there are more functions in there to manipulate global variables.

https://github.com/jeff-dh/SolidPython/blob/exp_solid/solid2/examples/17-greedy-scad-interface.py
https://github.com/jeff-dh/SolidPython/blob/exp_solid/solid2/extensions/greedy_scad_interface/scad_interface.py

**Comment by jeff-dh** [comment]
I though I -- at least wanted to -- completely wiped out the `file_header` parameter while refactoring that module, but apparently I didn't and ended up with an inconsistent api....

So, thx a lot for this issue and the corresponding fix!


============ back to global `$fn` ===========
Actually you don't need to explicitly import the `greedy_scad_interface_extensions` it's enabled by default, so calling `set_global_fn` is what you want. 

And I see the issue concerning the docs. Since I consider the examples as docs, I guess the underlying issue is that this functions should not be mentioned the first time in the very last example.... I'll have a look at it, if you have any suggestion, let me know!

**Comment by jeff-dh** [comment]
fixed the docs issue, it's now mentioned in the very first example :D

**Pull request merged**
