### PR TITLE
BOSL2 as submodule

### PR DESCRIPTION
**Pull request by ssuchter**
This PR changes the methodology of incorporation of BOSL2, but does not change the functionality or produced PIP package.

Changes:
- Utilize a submodule to incorporate BOSL2, instead of checking in a copy of its code
- Remove python stubs autogenerated from BOSL2 from git
- Create a prebuild script, called automatically by poetry build, which autogenerates the python stubs
- Display a friendly error message if there is an attempt to build poetry when the BOSL2 submodule isn't initialized

### CODE REVIEW

**Comment by jeff-dh** [comment]
So, I finally had a look at this pr and have a couple of thoughts about it:

I don't really like the idea of integrating the bosl2 generator script into the build process. First of all I don't see why this is necessary (if I update the bosl2 submodule manually I can call the generator script manually, that's fine for me). Furthermore up until now I had to manually fine tune the generated bosl2 stubs. I'm wondering how this works for you.
When I try to imported the vanilla bosl2 stubs I get this error:

```python
>>> from solid2.extensions.bosl2 import *
[...]
  File "/xxx/solid2/extensions/bosl2/bosl2_access_syntax_mixin.py", line 282
    def path_copies(self, path=None, n=None, spacing=None, sp=None, dist=None, rotate_children=None, dist=None, closed=None, **kwargs):
                                                                                                     ^^^^
SyntaxError: duplicate argument 'dist' in function definition
```
My solution to this up until now was to manually fine tune these issues. Furthermore I like to check the result and this includes checking the diffs which -- I guess -- is not possible with this solution.
In other words, I'd like to have manual control over updating the bosl2 stubs and I don't see any reason why we should change it. This also includes another issues, since bosl2 is still in beta status they still do make breaking changes! This means every bosl2 update is a potential breaking change in SolidPython2, there for forcing to manually check everything makes even more sense to me.

Furthermore I'm wondering whether your solution really includes the BOSL2 scad files into the pypi package. Because if I see it correctly you did exactly the same I did plus adding the prebuild integration. Where's the difference?

Further minor "issues" from my side:
- I don't like the version bump, because I don't want to release a new pypi package for this change, because it actually does not change the resulting package at all (or at least it should not change it)
- I don't like the generatedHeader because this is an artificial diff (makes it more complex to check diffs assuming we don't use prebuild generated stubs)
- I don't like the extra dependency to poethepoet unless it gives us a real advantage

So right now I'd prefer to cherry pick b346779b7f89977c40d6e74ab287e1d37768f039 and 40952745cf284ae641d6ad324b4264310673127a but I don't see the difference to my commits a couple of days ago which resulted in a pypi package that did not include the bosl2 scad files.

**Comment by ssuchter** [comment]
I totally take your main feedback! I was thinking that doing autogeneration alone was sufficient, and that is incorrect. One could argue about the value of testing the autogenerated files, but that doesn't exist yet and might be hard given the instability of BOSL2. This I agree with your main point of abandoning the approach this PR uses of depending on autogeneration.

This solution *does* include the BOSL2 scad files in the distribution. Proof:

```
GWLW4HPQVR:~/src% git clone --recurse-submodules -b BOSL2_as_submodule git@github.com:ssuchter/SolidPython.git ssuchter-SolidPython6
Cloning into 'ssuchter-SolidPython6'...
remote: Enumerating objects: 4700, done.
remote: Counting objects: 100% (1673/1673), done.
remote: Compressing objects: 100% (533/533), done.
remote: Total 4700 (delta 1194), reused 1540 (delta 1138), pack-reused 3027
Receiving objects: 100% (4700/4700), 2.46 MiB | 4.94 MiB/s, done.
Resolving deltas: 100% (3137/3137), done.
Submodule 'solid2/libs/BOSL2' (git@github.com:revarbat/BOSL2.git) registered for path 'solid2/libs/BOSL2'
Cloning into '/Users/ssuchter/src/ssuchter-SolidPython6/solid2/libs/BOSL2'...
remote: Enumerating objects: 13317, done.
remote: Counting objects: 100% (1069/1069), done.
remote: Compressing objects: 100% (475/475), done.
remote: Total 13317 (delta 665), reused 958 (delta 594), pack-reused 12248
Receiving objects: 100% (13317/13317), 7.08 MiB | 5.31 MiB/s, done.
Resolving deltas: 100% (9134/9134), done.
Submodule path 'solid2/libs/BOSL2': checked out '56031aea9a4012176bf59ff8d7b38e1d8f509fb0'
GWLW4HPQVR:~/src% cd ssuchter-SolidPython6
GWLW4HPQVR:~/src/ssuchter-SolidPython6% poetry build
Creating virtualenv solidpython2-V50O1bHQ-py3.10 in /Users/ssuchter/Library/Caches/pypoetry/virtualenvs
Preparing build environment with build-system requirements poetry-core>=1.0.0
Building solidpython2 (2.0.2)
GWLW4HPQVR:~/src/ssuchter-SolidPython6% tar tzf dist/solidpython2-2.0.2.tar.gz| grep BOSL2 | grep scad | head
solidpython2-2.0.2/solid2/libs/BOSL2/.github/openscad_docsgen.json
solidpython2-2.0.2/solid2/libs/BOSL2/.openscad_docsgen_rc
solidpython2-2.0.2/solid2/libs/BOSL2/.openscad_mdimggen_rc
solidpython2-2.0.2/solid2/libs/BOSL2/affine.scad
solidpython2-2.0.2/solid2/libs/BOSL2/attachments.scad
solidpython2-2.0.2/solid2/libs/BOSL2/ball_bearings.scad
solidpython2-2.0.2/solid2/libs/BOSL2/beziers.scad
solidpython2-2.0.2/solid2/libs/BOSL2/bosl1compat.scad
solidpython2-2.0.2/solid2/libs/BOSL2/bottlecaps.scad
solidpython2-2.0.2/solid2/libs/BOSL2/builtins.scad
```

I think the problem with the original attempts to utilize a submodule is that there was nothing checking that the submodule was initialized. If it's not initialized, there will be no files in it, and the packaging will not include its scad files. This is avoided in this PR because prebuild.py checks that the BOSL2 library has a known file in it, and fails the packaging without it. (To your question "Where's the difference" - that's where.)

To the other minor issues:
* Agree: Version bump is a misunderstanding on my part on the desired semantics of build system changes
* Agree: No point in generatedHeader if the files aren't fully autogenerated
* Mistake: The poethepoet isn't actually needed, that was a mistake in the comment. I thought I needed it, then figured out how to use core poetry, but forgot to update the client

I'm going to close this PR and create you a new one that doesn't do all the autogeneration gyrations I did, but does the submodule _and_ the submodule initialization check (in prebuild.py).

**Comment by jeff-dh** [comment]
Sounds good to me.

I had one more thought about it. I was wondering whether it would make more sense to put the bosl2 scad files somewhere into the bosl2-extension itself, because the bosl2 scad files are only used there.
I think we could add the submodule to `solid2/extensions/bosl2/scad` and that should work and makes more semantic sense.

Any thoughts / ideas about it?

**Comment by ssuchter** [comment]
I think that makes sense to me. I'm happy to help with that too. I feel
like I'm a decently heavy user of SolidPython, and happy to contribute back
so I'm not freeloading.

I'll do that in a separate PR, though, to keep change isolation good.

**Pull request closed without merging**
