### PR TITLE
accept dict or object as import_scad `destination` argument

### PR DESCRIPTION
**Pull request by ipsod**

### CODE REVIEW

**Comment by jeff-dh** [comment]
hmmmmm.....

```python
myDict = import_scad("MCAD").__dict__
```
?

**Comment by ipsod** [comment]
Oops.  I meant for either of these to work:
``` python
my_dict: dict = import_scad("MCAD", {})
my_obj: ExpSolidNamespace = import_scad("MCAD")
```

So, code should be:
``` python
def import_scad(filename, dest=None, use_not_include=True, skip_render=False):
    if dest == None:
        dest = ExpSolidNamespace(filename)

    try:
        to_dict = dest.__dict__
    except AttributeError:
        to_dict = dest

    load_scad_file_or_dir_into_dict(filename, to_dict, use_not_include, skip_render)

    return dest
```

or, instead of modifying, add a new function, would probably be better?

``` python
def import_scad_to_dict(filename, dest=None, use_not_include=True, skip_render=False):
    if dest == None:
        dest = {}

    load_scad_file_or_dir_into_dict(filename, to_dict, use_not_include, skip_render)

    return dest
```

plus add the new function to  __init__.py ?

**Comment by jeff-dh** [comment]
Furthermore -- it's still about the code from the other pr -- what about this:

```python
polyGear = import_scad("/gk/shapes/PolyGear/PolyGear.scad")
class What:
    def ever(...):
        [...]
        polyGear.spur_gear(....)
        [...]
```

**Comment by jeff-dh** [comment]
I don't see why you need it, this code should be fine:

```python
mydict: dict = import_scad("MCAD").__dict__
mynamespace: ExpSolidNamespace = import_scad("MCAD")
```

**Comment by ipsod** [comment]
That works, thanks!

**Pull request closed without merging**
